name: MacOS Release Build

on: 
  release:
    types: [published]

jobs:
    build-mac:
        runs-on: macos-latest

        steps:
            - name: Lade Code herunter
              uses: actions/checkout@v4

            - name: Installiere QT
              uses: jurplel/install-qt-action@v4
              with:
                version: '6.5.0'
            
            - name: Kompiliere Projekt
              run: |
                cd PokemonSoullinkTracker
                mkdir build
                cd build
                cmake ..
                cmake --build .

            - name: App in ZIP verpacken
              run: |
                  cd PokemonSoullinkTracker/build
                  zip -r PokemonTracker-Mac.zip *.app

            - name: Datei an GitHub Release anhängen
              uses: softprops/action-gh-release@v2
              with:
                files: PokemonSoullinkTracker/build/PokemonTracker-Mac.zip
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}